sudo: required
dist: trusty
language: cpp

env:
  global:
    - /usr/local/bin:$PATH

# NOTE: The COMPILER variable is unused. It simply makes the display on
# travis-ci.org more readable.
matrix:
    include:
        - compiler: gcc
          env: COMPILER=g++ C_COMPILER=gcc
        - compiler: gcc
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
              packages:
                - g++-6
          env:
            - COMPILER=g++-6 C_COMPILER=gcc-6
        - compiler: gcc
          addons:
            apt:
              packages:
                - g++-5
          env:
            - COMPILER=g++-5 C_COMPILER=gcc-5
        - compiler: clang
          env: COMPILER=clang++ C_COMPILER=clang
        - compiler: clang
          addons:
            apt:
              packages:
                libc++-dev
          env: COMPILER=clang++ C_COMPILER=clang EXTRA_FLAGS='-stdlib=libc++'
        # Clang w/ libc++
        - compiler: clang
          addons:
            apt:
              packages:
                clang-3.8
          env:
            - COMPILER=clang++-3.8 C_COMPILER=clang-3.8
        - compiler: clang
          addons:
            apt:
              packages:
                clang-3.8
                libc++-dev
          env:
            - COMPILER=clang++-3.8 C_COMPILER=clang-3.8 EXTRA_FLAGS='-stdlib=libc++'

before_script:
    - if [ -n "${LIBCXX_BUILD}" ]; then
        source .travis-libcxx-setup.sh;
      fi
    - mkdir build && cd build

script:
    - cmake -DCMAKE_C_COMPILER=${C_COMPILER} -DCMAKE_CXX_COMPILER=${COMPILER} "-DCMAKE_CXX_FLAGS=${EXTRA_FLAGS}" ..
    - make

sudo: required
